HW = <%=base%><%=homework %>
Q = questions/question_
QUESTIONS = <% for (var i = 1; i <= questions; i++) { %> $(Q)<%= i %>.tex<% } %>
UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
    PDFLATEX = pdflatex --shell-escape
    LATEX = latex --shell-escape
    BIBTEX = bibtex
endif
ifeq ($(UNAME), Darwin)
    PDFLATEX = /Library/TeX/texbin/pdflatex --shell-escape
    LATEX = /Library/TeX/texbin/latex --shell-escape
    BIBTEX = /Library/TeX/texbin/bibtex
endif

$(HW).pdf: $(HW).dvi
	$(PDFLATEX) $(HW).tex

$(HW).dvi: $(HW).tex $(QUESTIONS)
	$(LATEX) $(HW).tex

citations: $(HW).bbl

$(HW).bbl: $(HW).bib
	$(BIBTEX) $(HW) && $(LATEX) $(HW).tex && $(LATEX) $(HW).tex


<% for (var i = 1; i <= questions; i++) { %>
$(Q)<%= i %>.tex:

<% } %>

clean:
	rm $(HW).pdf $(HW).dvi $(HW).aux $(HW).log $(HW).bbl $(HW).blg
