HW = hw<%=homework %>
Q = questions/question_
QUESTIONS = <% for (var i = 1; i <= questions; i++) { %> $(Q)<%= i %>.tex<% } %>
UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
    PDFLATEX = latex
    LATEX = latex
endif
ifeq ($(UNAME), Darwin)
    PDFLATEX = /Library/TeX/texbin/pdflatex
    LATEX = /Library/TeX/texbin/latex
endif

$(HW).pdf: $(HW).dvi
	$(PDFLATEX) $(HW).tex

$(HW).dvi: $(HW).tex $(QUESTIONS)
	$(LATEX) $(HW).tex

<% for (var i = 1; i <= questions; i++) { %>
$(Q)<%= i %>.tex:

<% } %>

clean:
	rm $(HW).pdf $(HW).dvi $(HW).aux $(HW).log
